login_system/urls.py
from django.conf.urls import url
from . import views

app_name = 'login_system'

urlpatterns = [

    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from login_system import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("system/", include("server.urls")),
    url(r'^login_system/', include('login_system.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='speical'),
    url(r'^$', views.index, name='index'),
]

login_system/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

def __str__(self):
  return self.user.username

login_system/forms.py
from django import forms
from login_system.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class RegistrationForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    password_confirm=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

login_system/views.py
from django.shortcuts import render
from login_system.forms import UserForm, RegistrationForm
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'login_system/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = RegistrationForm(data=request.POST)
        if user_form.is_valid() and user_form.cleaned_data['password'] == user_form.cleaned_data['password_confirm']:
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        elif user_form.data['password'] != user_form.data['password_confirm']:
            user_form.add_error('password_confirm', 'The passwords do not match')
        else:
            print(user_form.error)
    else:
        user_form = RegistrationForm()
    return render(request, 'login_system/registration.html',{'registration_form':RegistrationForm, 'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tries to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login_system/login.html', {})

templates/login_system/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Authentication System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"></head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'login_system:register' %}">Register</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login_system:user_login' %}">Login</a></li>
          {% endif %}</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/login_system/index.html
{% extends "login_system/base.html" %}
{% block body_block %}<div class="container">
  <div class="jumbotron">
    <h1>Welcome !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>{% endblock %}

templates/login_system/login.html
{% extends 'login_system/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1><form method="post" action="{% url 'login_system:user_login' %}">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password"><input type="submit" name="" value="Login"></form></div>
  </div>
{% endblock %}

templates/login_system/registration.html
{% extends "login_system/base.html" %}
{% load static %}{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3><form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ registration_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}